stages:
  prepare:
    cmd: python src/prepare.py data/raw/healthcare-dataset-stroke-data.csv data/prepared
    deps:
      - data/raw/healthcare-dataset-stroke-data.csv
      - src/prepare.py
    outs:
      - data/prepared
  train:
    cmd: python src/train.py data/prepared/train.csv data/prepared/test.csv data/models
    deps:
      - data/prepared/train.csv
      - data/prepared/test.csv
      - src/train.py
    outs:
      - data/models
